### PR TITLE
RFC proposal

### PR DESCRIPTION
**Pull request by franciscoaguirre**
I propose an RFC process akin to the one in https://github.com/w3f/PPPs to propose changes to the XCM format regardless of implementation.

### CODE REVIEW

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/xcm-rfc-process/2447/1

**Comment by vstam1** [comment]
I like the setup of the RFC process to organise the development of new xcm features and open the discussion about the format to the community. One thing I would like to see is some kind of priority system. Each RFC of course already has a version matched to it. Do we want this version set by the community or the maintainers? And do we want to use this version as a way to prioritise features? Furthermore, I would like to see some impact section where the impact of the feature is defined. For example the impact of a new instruction will possibly be lower than the impact of a change to an existing instruction. Additionally to the impact section, we can assign the impact as an additional field in the frontmatter. 

Let me know what you think

**Comment by franciscoaguirre** [comment]
@vstam1 I think versions should be set by the maintainers, sort of how RFC numbers should also be set after they have been accepted.

The version could be use as a sort of priority (lower-numbered versions come first) but that is mostly useful if we stick to adding only a small set of features per version.

Let's say we have 3 accepted RFCs, and maintainers decided the first two aim for version X while the last one aims for some version Y > X.
Then we'd need to keep them as accepted while the main implementations (right now only xcm-executor) add the changes and change them to enacted once they are done.
Once the version is complete, we tag the commit.
Then we start with the new version.
Does that flow make sense?

**Comment by franciscoaguirre** [comment]
@vstam1

Regarding the impact section:
> For example the impact of a new instruction will possibly be lower than the impact of a change to an existing instruction.

Does this mean that the "impact" is some degree of breaking changes? Are you envisioning something like the following?
- Impact: 0 -> Breaking changes
- Impact: 1 -> High
- Impact: 2 -> Low
- Impact: 3 -> Trivial

**Comment by franciscoaguirre** [comment]
@KiChjang 

I thought definitely the fellowship instead of parity, but I didn't know about the upcoming parachain fellowship. We should probably talk to them about this. What's a good starting point for that?

I don't know how long the general review period should be. Looking at the rust RFCs for example, that period is only done when a maintainer proposes to start a "final comment period", and those last 10 calendar days. This sounds reasonable. What do you think?

**Comment by vstam1** [comment]
>  Does this mean that the "impact" is some degree of breaking changes? Are you envisioning something like the following?
Yeah I think this division of impact could be useful.

**Comment by franciscoaguirre** [comment]
@vstam1 I added the "Impact" field to the frontmatter and section

**Review by vstam1 — APPROVED** [review]

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/xcm-rfc-process/2447/2

**Pull request merged**
